name: 'CI'

on:
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        java: [ 11 ]
        node: [ '16' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (Java ${{ matrix.java }} Node ${{ matrix.node }})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.Java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Build Language Server
        run: language-server/gradlew -p language-server/ build --no-daemon
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: success() || failure()        # upload test results even if previous step failed
        with:
          name: test-results-${{ matrix.os }}
          path: language-server/org.big.erd/build/test-results/test/TEST-*.xml, language-server/org.big.erd.ide/build/test-results/test/TEST-*.xml
      - name: Build Webview
        run: yarn --cwd webview
      - name: Build Extension
        run: yarn --cwd extension
